package com.example.dogimagegenerator.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

// Represents the DogImage table in the Room database
@Entity(tableName = "dog_images")
data class DogImage(
    @PrimaryKey(autoGenerate = true) val id: Int = 0, // Unique identifier for each entry, auto-generated by Room
    val imageUrl: String // URL of the dog image
)
